Watering system with Arudino UNO without Arduino libraries: TWI Library <twi.h>
TWI Library <twi.h>
I2C/TWI library for AVR-GCC.
Other definitions
void twi_init (void)
Initialize TWI unit, enable internal pull-ups, and set SCL frequency.
void twi_start (void)
Start communication on I2C/TWI bus.
uint8_t twi_write (uint8_t data)
Send one byte to I2C/TWI Slave device.
uint8_t twi_read (uint8_t ack)
Read one byte from I2C/TWI Slave device and acknowledge it by ACK or NACK.
void twi_stop (void)
Generates Stop condition on I2C/TWI bus.
uint8_t twi_test_address (uint8_t adr)
Test presence of one I2C device on the bus.
#define TWI_WRITE 0
Mode for writing to I2C/TWI device.
#define TWI_READ 1
Mode for reading from I2C/TWI device.
#define TWI_ACK 0
ACK value for writing to I2C/TWI bus.
#define TWI_NACK 1
NACK value for writing to I2C/TWI bus.
#define DDR(_x) (*(&_x - 1))
Address of Data Direction Register of port _x.
#define PIN(_x) (*(&_x - 2))
Address of input register of port _x.
Definition of frequencies
#define F_CPU 16000000
CPU frequency in Hz required TWI_BIT_RATE_REG.
#define F_SCL 100000
I2C/TWI bit rate. Must be greater than 31000.
#define TWI_BIT_RATE_REG ((F_CPU/F_SCL - 16) / 2)
TWI bit rate register value.
Definition of ports and pins
#define TWI_PORT PORTC
Port of TWI unit.
#define TWI_SDA_PIN 4
SDA pin of TWI unit.
#define TWI_SCL_PIN 5
SCL pin of TWI unit.
Detailed Description
I2C/TWI library for AVR-GCC.
#include <twi.h>
This library defines functions for the TWI (I2C) communication between AVR and Slave device(s). Functions use internal TWI module of AVR.
Note
Only Master transmitting and Master receiving modes are implemented. Based on Microchip Atmel ATmega16 and ATmega328P manuals.
Author
Tomas Fryza, Dept. of Radio Electronics, Brno University of Technology, Czechia
Copyright
(c) 2018 Tomas Fryza, This work is licensed under the terms of the MIT license
Macro Definition Documentation
DDR
#define DDR (_x) (*(&_x - 1))
Address of Data Direction Register of port _x.
F_CPU
#define F_CPU 16000000
CPU frequency in Hz required TWI_BIT_RATE_REG.
F_SCL
#define F_SCL 100000
I2C/TWI bit rate. Must be greater than 31000.
PIN
#define PIN (_x) (*(&_x - 2))
Address of input register of port _x.
TWI_ACK
#define TWI_ACK 0
ACK value for writing to I2C/TWI bus.
TWI_BIT_RATE_REG
#define TWI_BIT_RATE_REG ((F_CPU/F_SCL - 16) / 2)
TWI bit rate register value.
TWI_NACK
#define TWI_NACK 1
NACK value for writing to I2C/TWI bus.
TWI_PORT
#define TWI_PORT PORTC
Port of TWI unit.
TWI_READ
#define TWI_READ 1
Mode for reading from I2C/TWI device.
TWI_SCL_PIN
#define TWI_SCL_PIN 5
SCL pin of TWI unit.
TWI_SDA_PIN
#define TWI_SDA_PIN 4
SDA pin of TWI unit.
TWI_WRITE
#define TWI_WRITE 0
Mode for writing to I2C/TWI device.
Function Documentation
twi_init()
void twi_init (void)
Initialize TWI unit, enable internal pull-ups, and set SCL frequency.
Implementation notes:
AVR internal pull-up resistors at pins TWI_SDA_PIN and TWI_SCL_PIN are enabled
TWI bit rate register value is calculated as follows fscl = fcpu/(16 + 2*TWBR)
Returns
none
{
    /* Enable internal pull-up resistors */
    DDR(TWI_PORT) &= ~((1<<TWI_SDA_PIN) | (1<<TWI_SCL_PIN));
    TWI_PORT |= (1<<TWI_SDA_PIN) | (1<<TWI_SCL_PIN);
    /* Set SCL frequency */
    TWSR &= ~((1<<TWPS1) | (1<<TWPS0));
    TWBR = TWI_BIT_RATE_REG;
}
Referenced by oled_init(), and sensors_init().
twi_read()
uint8_t twi_read (uint8_t ack)
Read one byte from I2C/TWI Slave device and acknowledge it by ACK or NACK.
Parameters
ack - ACK/NACK value to be transmitted
Returns
Received data byte
{
    if (ack == TWI_ACK)
        TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWEA);
    else
        TWCR = (1<<TWINT) | (1<<TWEN);
    for(uint32_t i = 0; i < TWI_TIMEOUT && ((TWCR & (1<<TWINT)) == 0); i++) asm("NOP");
    return (TWDR);
}
Referenced by sensors_update_dataset().
twi_start()
void twi_start (void)
Start communication on I2C/TWI bus.
Returns
none
{
    /* Send Start condition */
    TWCR = (1<<TWINT) | (1<<TWSTA) | (1<<TWEN);
    for(uint32_t i = 0; i < TWI_TIMEOUT && ((TWCR & (1<<TWINT)) == 0); i++) asm("NOP");
}
Referenced by oled_command(), oled_data(), sensors_update_dataset(), and twi_test_address().
twi_stop()
void twi_stop (void)
Generates Stop condition on I2C/TWI bus.
Returns
none
{
    /* Generate Stop condition on I2C/TWI bus */
    TWCR = (1<<TWINT) | (1<<TWSTO) | (1<<TWEN);
}
Referenced by oled_command(), oled_data(), sensors_update_dataset(), and twi_test_address().
twi_test_address()
uint8_t twi_test_address (uint8_t adr)
Test presence of one I2C device on the bus.
Parameters
adr Slave address
Returns
ACK/NACK received value
Return values
0 - ACK has been received
1 - NACK has been received
{
    uint8_t ack;  // ACK response from Slave
    twi_start();
    ack = twi_write((adr<<1) | TWI_WRITE);
    twi_stop();
    return ack;
}
twi_write()
uint8_t twi_write (uint8_t data)
Send one byte to I2C/TWI Slave device.
Parameters
data Byte to be transmitted
Returns
ACK/NACK received value
Return values
0 - ACK has been received
1 - NACK has been received
Note
Function returns 0 if 0x18, 0x28, or 0x40 status code is detected
0x18: SLA+W has been transmitted and ACK has been received
0x28: Data byte has been transmitted and ACK has been received
0x40: SLA+R has been transmitted and ACK has been received
{
    uint8_t twi_status;
    /* Send SLA+R, SLA+W, or data byte on I2C/TWI bus */
    TWDR = data;
    TWCR = (1<<TWINT) | (1<<TWEN);
    for(uint32_t i = 0; i < TWI_TIMEOUT && ((TWCR & (1<<TWINT)) == 0); i++) asm("NOP");
    /* Check value of TWI status register */
    twi_status = TWSR & 0xf8;
    /* Status Code:
          * 0x18: SLA+W has been transmitted and ACK received
          * 0x28: Data byte has been transmitted and ACK has been received
          * 0x40: SLA+R has been transmitted and ACK received
    */
    if (twi_status == 0x18 || twi_status == 0x28 || twi_status == 0x40)
        return 0;   /* ACK received */
    else
        return 1;   /* NACK received */
}
Referenced by oled_command(), oled_data(), sensors_update_dataset(), and twi_test_address().