Watering system with Arudino UNO without Arduino libraries: UART Library <uart.h>
UART Library <uart.h>
Interrupt UART library using the built-in UART with transmit and receive circular buffers.
Macros
#define UART_BAUD_SELECT(baudRate, xtalCpu) (((xtalCpu) + 8UL * (baudRate)) / (16UL * (baudRate)) -1UL)
UART Baudrate Expression.
#define UART_BAUD_SELECT_DOUBLE_SPEED(baudRate, xtalCpu) (((((xtalCpu) + 4UL * (baudRate)) / (8UL * (baudRate)) -1UL)) | 0x8000)
UART Baudrate Expression for ATmega double speed mode.
#define UART_RX_BUFFER_SIZE 32
Size of the circular receive buffer, must be power of 2.
#define UART_TX_BUFFER_SIZE 256
Size of the circular transmit buffer, must be power of 2.
#define UART_FRAME_ERROR 0x1000
Framing Error by UART
#define UART_OVERRUN_ERROR 0x0800
Overrun condition by UART
#define UART_PARITY_ERROR 0x0400
Parity Error by UART
#define UART_BUFFER_OVERFLOW 0x0200
receive ringbuffer overflow
#define UART_NO_DATA 0x0100
no receive data available
#define uart_puts_P(__s) uart_puts_p(PSTR(__s))
Macro to automatically put a string constant into program memory.
#define uart1_puts_P(__s) uart1_puts_p(PSTR(__s))
Macro to automatically put a string constant into program memory.
Functions
void uart_init (unsigned int baudrate)
Initialize UART and set baudrate.
unsigned int uart_getc (void)
Get received byte from ringbuffer.
void uart_putc (unsigned char data)
Put byte to ringbuffer for transmitting via UART.
void uart_puts (const char *s)
Put string to ringbuffer for transmitting via UART.
void uart_puts_p (const char *s)
Put string from program memory to ringbuffer for transmitting via UART.
void uart1_init (unsigned int baudrate)
Initialize USART1 (only available on selected ATmegas)
unsigned int uart1_getc (void)
Get received byte of USART1 from ringbuffer. (only available on selected ATmega)
void uart1_putc (unsigned char data)
Put byte to ringbuffer for transmitting via USART1 (only available on selected ATmega)
void uart1_puts (const char *s)
Put string to ringbuffer for transmitting via USART1 (only available on selected ATmega)
void uart1_puts_p (const char *s)
Put string from program memory to ringbuffer for transmitting via USART1 (only available on selected ATmega)
Detailed Description
Interrupt UART library using the built-in UART with transmit and receive circular buffers.
#include <uart.h>
This library can be used to transmit and receive data through the built in UART.
An interrupt is generated when the UART has finished transmitting or receiving a byte. The interrupt handling routines use circular buffers for buffering received and transmitted data.
The UART_RX_BUFFER_SIZE and UART_TX_BUFFER_SIZE constants define the size of the circular buffers in bytes. Note that these constants must be a power of 2. You may need to adapt these constants to your target and your application by adding CDEFS += -DUART_RX_BUFFER_SIZE=nn -DUART_TX_BUFFER_SIZE=nn to your Makefile.
Note
Based on Atmel Application Note AVR306
Author
Peter Fleury pfleu.nosp@m.ry@g.nosp@m.mx.ch http://tinyurl.com/peterfleury
Copyright
(C) 2015 Peter Fleury, GNU General Public License Version 3
Macro Definition Documentation
uart1_puts_P
#define uart1_puts_P (__s) uart1_puts_p(PSTR(__s))
Macro to automatically put a string constant into program memory.
UART_BAUD_SELECT
#define UART_BAUD_SELECT (baudRate, xtalCpu) (((xtalCpu) + 8UL * (baudRate)) / (16UL * (baudRate)) -1UL)
UART Baudrate Expression.
Parameters
xtalCpu system clock in Mhz, e.g. 4000000UL for 4Mhz
baudRate baudrate in bps, e.g. 1200, 2400, 9600
UART_BAUD_SELECT_DOUBLE_SPEED
#define UART_BAUD_SELECT_DOUBLE_SPEED (baudRate, xtalCpu) (((((xtalCpu) + 4UL * (baudRate)) / (8UL * (baudRate)) -1UL)) | 0x8000)
UART Baudrate Expression for ATmega double speed mode.
Parameters
xtalCpu system clock in Mhz, e.g. 4000000UL for 4Mhz
baudRate baudrate in bps, e.g. 1200, 2400, 9600
UART_BUFFER_OVERFLOW
#define UART_BUFFER_OVERFLOW 0x0200
receive ringbuffer overflow
UART_FRAME_ERROR
#define UART_FRAME_ERROR 0x1000
Framing Error by UART
UART_NO_DATA
#define UART_NO_DATA 0x0100
no receive data available
UART_OVERRUN_ERROR
#define UART_OVERRUN_ERROR 0x0800
Overrun condition by UART
UART_PARITY_ERROR
#define UART_PARITY_ERROR 0x0400
Parity Error by UART
uart_puts_P
#define uart_puts_P (__s) uart_puts_p(PSTR(__s))
Macro to automatically put a string constant into program memory.
UART_RX_BUFFER_SIZE
#define UART_RX_BUFFER_SIZE 32
Size of the circular receive buffer, must be power of 2.
You may need to adapt this constant to your target and your application by adding CDEFS += -DUART_RX_BUFFER_SIZE=nn to your Makefile.
UART_TX_BUFFER_SIZE
#define UART_TX_BUFFER_SIZE 256
Size of the circular transmit buffer, must be power of 2.
You may need to adapt this constant to your target and your application by adding CDEFS += -DUART_TX_BUFFER_SIZE=nn to your Makefile.
Function Documentation
uart1_getc()
unsigned int uart1_getc (void)
Get received byte of USART1 from ringbuffer. (only available on selected ATmega)
See also
uart_getc
uart1_init()
void uart1_init (unsigned int baudrate)
Initialize USART1 (only available on selected ATmegas)
See also
uart_init
uart1_putc()
void uart1_putc (unsigned char data)
Put byte to ringbuffer for transmitting via USART1 (only available on selected ATmega)
See also
uart_putc
uart1_puts()
void uart1_puts (const char * s)
Put string to ringbuffer for transmitting via USART1 (only available on selected ATmega)
See also
uart_puts
uart1_puts_p()
void uart1_puts_p (const char * s)
Put string from program memory to ringbuffer for transmitting via USART1 (only available on selected ATmega)
See also
uart_puts_p
uart_getc()
unsigned int uart_getc (void)
Get received byte from ringbuffer.
Returns in the lower byte the received character and in the higher byte the last receive error. UART_NO_DATA is returned when no data is available.
Returns
lower byte: received byte from ringbuffer
higher byte: last receive status
0 successfully received data from UART
UART_NO_DATA
no receive data available
UART_BUFFER_OVERFLOW
Receive ringbuffer overflow. We are not reading the receive buffer fast enough, one or more received character have been dropped
UART_OVERRUN_ERROR
Overrun condition by UART. A character already present in the UART UDR register was not read by the interrupt handler before the next character arrived, one or more received characters have been dropped.
UART_FRAME_ERROR
Framing Error by UART
{
    unsigned char tmptail;
    unsigned char data;
    unsigned char lastRxError;
    if ( UART_RxHead == UART_RxTail ) {
        return UART_NO_DATA;   /* no data available */
    }
    /* calculate buffer index */
    tmptail = (UART_RxTail + 1) & UART_RX_BUFFER_MASK;
    /* get data from receive buffer */
    data = UART_RxBuf[tmptail];
    lastRxError = UART_LastRxError;
    /* store buffer index */
    UART_RxTail = tmptail;
    UART_LastRxError = 0;
    return (lastRxError << 8) + data;
}/* uart_getc */
Referenced by cmd_handler(), and main().
uart_init()
void uart_init (unsigned int baudrate)
Initialize UART and set baudrate.
Parameters
baudrate Specify baudrate using macro UART_BAUD_SELECT()
Returns
none
{
    UART_TxHead = 0;
    UART_TxTail = 0;
    UART_RxHead = 0;
    UART_RxTail = 0;
#ifdef UART_TEST
#ifndef UART0_BIT_U2X
#warning "UART0_BIT_U2X not defined"
#endif
#ifndef UART0_UBRRH
#warning "UART0_UBRRH not defined"
#endif
#ifndef UART0_CONTROLC
#warning "UART0_CONTROLC not defined"
#endif
#if defined(URSEL) || defined(URSEL0)
#ifndef UART0_BIT_URSEL
#warning "UART0_BIT_URSEL not defined"
#endif
#endif
#endif
    /* Set baud rate */
    if ( baudrate & 0x8000 )
    {
        #if UART0_BIT_U2X
        UART0_STATUS = (1<<UART0_BIT_U2X);  //Enable 2x speed
        #endif
    }
    #if defined(UART0_UBRRH)
    UART0_UBRRH = (unsigned char)((baudrate>>8)&0x80) ;
    #endif
    UART0_UBRRL = (unsigned char) (baudrate&0x00FF);
    /* Enable USART receiver and transmitter and receive complete interrupt */
    UART0_CONTROL = _BV(UART0_BIT_RXCIE)|(1<<UART0_BIT_RXEN)|(1<<UART0_BIT_TXEN);
    /* Set frame format: asynchronous, 8data, no parity, 1stop bit */
    #ifdef UART0_CONTROLC
    #ifdef UART0_BIT_URSEL
    UART0_CONTROLC = (1<<UART0_BIT_URSEL)|(1<<UART0_BIT_UCSZ1)|(1<<UART0_BIT_UCSZ0);
    #else
    UART0_CONTROLC = (1<<UART0_BIT_UCSZ1)|(1<<UART0_BIT_UCSZ0);
    #endif
    #endif
}/* uart_init */
Referenced by main().
uart_putc()
void uart_putc (unsigned char data)
Put byte to ringbuffer for transmitting via UART.
Parameters
data byte to be transmitted
Returns
none
{
    unsigned char tmphead;
    tmphead  = (UART_TxHead + 1) & UART_TX_BUFFER_MASK;
    while ( tmphead == UART_TxTail ){
        ;/* wait for free space in buffer */
    }
    UART_TxBuf[tmphead] = data;
    UART_TxHead = tmphead;
    /* enable UDRE interrupt */
    UART0_CONTROL    |= _BV(UART0_UDRIE);
}/* uart_putc */
Referenced by cmd_handler(), main(), uart_puts(), and uart_puts_p().
uart_puts()
void uart_puts (const char * s)
Put string to ringbuffer for transmitting via UART.
The string is buffered by the uart library in a circular buffer and one character at a time is transmitted to the UART using interrupts. Blocks if it can not write the whole string into the circular buffer.
Parameters
s string to be transmitted
Returns
none
{
    while (*s)
      uart_putc(*s++);
}/* uart_puts */
Referenced by cmd_handler(), and main().
uart_puts_p()
void uart_puts_p (const char * s)
Put string from program memory to ringbuffer for transmitting via UART.
The string is buffered by the uart library in a circular buffer and one character at a time is transmitted to the UART using interrupts. Blocks if it can not write the whole string into the circular buffer.
Parameters
s program memory string to be transmitted
Returns
none
See also
uart_puts_P
{
    register char c;
    while ( (c = pgm_read_byte(progmem_s++)) )
      uart_putc(c);
}/* uart_puts_p */