Watering system with Arudino UNO without Arduino libraries: GPIO Library <gpio.h>
GPIO Library <gpio.h>
GPIO library for AVR-GCC.
Functions
void GPIO_mode_output (volatile uint8_t *reg, uint8_t pin)
Configure one output pin.
void GPIO_mode_input_pullup (volatile uint8_t *reg, uint8_t pin)
Configure one input pin and enable pull-up.
void GPIO_write_low (volatile uint8_t *reg, uint8_t pin)
Write one pin to low value.
void GPIO_write_high (volatile uint8_t *reg, uint8_t pin)
Write one pin to high value.
void GPIO_write (volatile uint8_t *reg, uint8_t pin, uint8_t value)
Write one pin to specific value.
uint8_t GPIO_read (volatile uint8_t *reg, uint8_t pin)
Read a value from input pin.
Detailed Description
GPIO library for AVR-GCC.
#include <gpio.h>
The library contains functions for controlling AVRs' gpio pin(s).
Note
Based on AVR Libc Reference Manual. Tested on ATmega328P (Arduino Uno), 16 MHz, AVR 8-bit Toolchain 3.6.2.
Author
Tomas Fryza, Dept. of Radio Electronics, Brno University of Technology, Czechia
Copyright
(c) 2019 Tomas Fryza, This work is licensed under the terms of the MIT license
Function Documentation
GPIO_mode_input_pullup()
void GPIO_mode_input_pullup (volatile uint8_t * reg, uint8_t pin)
Configure one input pin and enable pull-up.
Parameters
reg Address of Data Direction Register, such as &DDRB
pin Pin designation in the interval 0 to 7
Returns
none
{
    *reg = *reg & ~(1<<pin);  // Data Direction Register
    reg++;                    // Change pointer to Data Register
    *reg = *reg | (1<<pin);   // Data Register
}
GPIO_mode_output()
void GPIO_mode_output (volatile uint8_t * reg, uint8_t pin)
Configure one output pin.
Parameters
reg Address of Data Direction Register, such as &DDRB
pin Pin designation in the interval 0 to 7
Returns
none
{
    *reg = *reg | (1<<pin);
}
Referenced by main().
GPIO_read()
uint8_t GPIO_read (volatile uint8_t * reg, uint8_t pin)
Read a value from input pin.
Parameters
reg Address of Pin Register, such as &PINB
pin Pin designation in the interval 0 to 7
Returns
Pin value
{
    uint8_t temp;
    temp = *reg & (1<<pin);
    if (temp != 0) {
        return 1;
    }
    else {
        return 0;
    }
}
GPIO_write()
void GPIO_write (volatile uint8_t * reg, uint8_t pin, uint8_t value)
Write one pin to specific value.
Parameters
reg Address of Port Register, such as &PORTB
pin Pin designation in the interval 0 to 7
value 0=LOW, 1=HIGH
Returns
none
{
    if(value) GPIO_write_high(reg, pin);
    else GPIO_write_low(reg, pin);
}
GPIO_write_high()
void GPIO_write_high (volatile uint8_t * reg, uint8_t pin)
Write one pin to high value.
Parameters
reg Address of Port Register, such as &PORTB
pin Pin designation in the interval 0 to 7
Returns
none
{
    *reg = *reg | (1<<pin);
}
Referenced by GPIO_write(), and servo_50us_interrupt_handler().
GPIO_write_low()
void GPIO_write_low (volatile uint8_t * reg, uint8_t pin)
Write one pin to low value.
Parameters
reg Address of Port Register, such as &PORTB
pin Pin designation in the interval 0 to 7
Returns
none
{
    *reg = *reg & ~(1<<pin);
}
Referenced by GPIO_write(), servo_50us_interrupt_handler(), and servo_init().