Watering system with Arudino UNO without Arduino libraries: lib/oled/oled.h File Reference
oled.h File Reference
#include <inttypes.h>
#include <avr/pgmspace.h>
#include "twi.h"
Macros
#define I2C
#define SH1106
#define GRAPHICMODE
#define FONT ssd1306oled_font
#define OLED_I2C_ADR (0x3c)
#define YES 1
#define NORMALSIZE 1
#define DOUBLESIZE 2
#define OLED_DISP_OFF 0xAE
#define OLED_DISP_ON 0xAF
#define WHITE 0x01
#define BLACK 0x00
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
Functions
void oled_command (uint8_t cmd[], uint8_t size)
void oled_data (uint8_t data[], uint16_t size)
void oled_init (uint8_t dispAttr)
void oled_home (void)
void oled_invert (uint8_t invert)
void oled_sleep (uint8_t sleep)
void oled_set_contrast (uint8_t contrast)
void oled_puts (const char *s)
void oled_puts_p (const char *progmem_s)
void oled_clrscr (void)
void oled_gotoxy (uint8_t x, uint8_t y)
void oled_goto_xpix_y (uint8_t x, uint8_t y)
void oled_putc (char c)
void oled_charMode (uint8_t mode)
void oled_flip (uint8_t flipping)
uint8_t oled_drawPixel (uint8_t x, uint8_t y, uint8_t color)
uint8_t oled_drawLine (uint8_t x1, uint8_t y1, uint8_t x2, uint8_t y2, uint8_t color)
uint8_t oled_drawRect (uint8_t px1, uint8_t py1, uint8_t px2, uint8_t py2, uint8_t color)
uint8_t oled_fillRect (uint8_t px1, uint8_t py1, uint8_t px2, uint8_t py2, uint8_t color)
uint8_t oled_drawCircle (uint8_t center_x, uint8_t center_y, uint8_t radius, uint8_t color)
uint8_t oled_fillCircle (uint8_t center_x, uint8_t center_y, uint8_t radius, uint8_t color)
uint8_t oled_drawBitmap (uint8_t x, uint8_t y, const uint8_t picture[], uint8_t width, uint8_t height, uint8_t color)
void oled_display (void)
void oled_clear_buffer (void)
uint8_t oled_check_buffer (uint8_t x, uint8_t y)
void oled_display_block (uint8_t x, uint8_t line, uint8_t width)
Macro Definition Documentation
BLACK
#define BLACK 0x00
DISPLAY_HEIGHT
#define DISPLAY_HEIGHT 64
DISPLAY_WIDTH
#define DISPLAY_WIDTH 128
DOUBLESIZE
#define DOUBLESIZE 2
FONT
#define FONT ssd1306oled_font
GRAPHICMODE
#define GRAPHICMODE
I2C
#define I2C
NORMALSIZE
#define NORMALSIZE 1
OLED_DISP_OFF
#define OLED_DISP_OFF 0xAE
OLED_DISP_ON
#define OLED_DISP_ON 0xAF
OLED_I2C_ADR
#define OLED_I2C_ADR (0x3c)
SH1106
#define SH1106
WHITE
#define WHITE 0x01
YES
#define YES 1
Function Documentation
oled_charMode()
void oled_charMode (uint8_t mode)
{
    charMode = mode;
}
Referenced by display_init().
oled_check_buffer()
uint8_t oled_check_buffer (uint8_t x, uint8_t y)
{
    if( x > DISPLAY_WIDTH-1 || y > (DISPLAY_HEIGHT-1)) return 0; // out of Display
    return displayBuffer[(y / (DISPLAY_HEIGHT/8))][x] & (1 << (y % (DISPLAY_HEIGHT/8)));
}
oled_clear_buffer()
void oled_clear_buffer (void)
{
    for (uint8_t i = 0; i < DISPLAY_HEIGHT/8; i++){
        memset(displayBuffer[i], 0x00, sizeof(displayBuffer[i]));
    }
}
oled_clrscr()
void oled_clrscr (void)
                      {
#ifdef GRAPHICMODE
    for (uint8_t i = 0; i < DISPLAY_HEIGHT/8; i++){
        memset(displayBuffer[i], 0x00, sizeof(displayBuffer[i]));
        oled_gotoxy(0,i);
        oled_data(displayBuffer[i], sizeof(displayBuffer[i]));
    }
#elif defined TEXTMODE
    uint8_t displayBuffer[DISPLAY_WIDTH];
    memset(displayBuffer, 0x00, sizeof(displayBuffer));
    for (uint8_t i = 0; i < DISPLAY_HEIGHT/8; i++){
        oled_gotoxy(0,i);
        oled_data(displayBuffer, sizeof(displayBuffer));
    }
#endif
    oled_home();
}
Referenced by display_init(), and oled_init().
oled_command()
void oled_command (uint8_t cmd[], uint8_t size)
{
#if defined I2C
    twi_start();
    twi_write((OLED_I2C_ADR<<1) | TWI_WRITE);
    // i2c_start((OLED_I2C_ADR << 1) | 0);
    twi_write(0x00);
    // i2c_byte(0x00);    // 0x00 for command, 0x40 for data
    for (uint8_t i=0; i<size; i++) {
        twi_write(cmd[i]);
        // i2c_byte(cmd[i]);
    }
    twi_stop();
#elif defined SPI
    OLED_PORT &= ~(1 << CS_PIN);
    OLED_PORT &= ~(1 << DC_PIN);
    for (uint8_t i=0; i<size; i++) {
        SPDR = cmd[i];
        while(!(SPSR & (1<<SPIF)));
    }
    OLED_PORT |= (1 << CS_PIN);
#endif
}
Referenced by oled_flip(), oled_goto_xpix_y(), oled_init(), oled_invert(), oled_putc(), oled_set_contrast(), and oled_sleep().
oled_data()
void oled_data (uint8_t data[], uint16_t size)
{
#if defined I2C
    twi_start();
    twi_write((OLED_I2C_ADR<<1) | TWI_WRITE);
    // i2c_start((OLED_I2C_ADR << 1) | 0);
    twi_write(0x40);
    // i2c_byte(0x40);    // 0x00 for command, 0x40 for data
    for (uint16_t i = 0; i<size; i++) {
        twi_write(data[i]);
        // i2c_byte(data[i]);
    }
    twi_stop();
    // i2c_stop();
#elif defined SPI
    OLED_PORT &= ~(1 << CS_PIN);
    OLED_PORT |= (1 << DC_PIN);
    for (uint16_t i = 0; i<size; i++) {
        SPDR = data[i];
        while(!(SPSR & (1<<SPIF)));
    }
    OLED_PORT |= (1 << CS_PIN);
#endif
}
Referenced by oled_clrscr(), oled_display(), oled_display_block(), and oled_putc().
oled_display()
void oled_display (void)
                    {
#if defined (SSD1306) || defined (SSD1309)
    oled_gotoxy(0,0);
    oled_data(&displayBuffer[0][0], DISPLAY_WIDTH*DISPLAY_HEIGHT/8);
#elif defined SH1106
    for (uint8_t i = 0; i < DISPLAY_HEIGHT/8; i++){
        oled_gotoxy(0,i);
        oled_data(displayBuffer[i], sizeof(displayBuffer[i]));
    }
#endif
}
Referenced by display_init(), and display_show_data().
oled_display_block()
void oled_display_block (uint8_t x, uint8_t line, uint8_t width)
{
    if (line > (DISPLAY_HEIGHT/8-1) || x > DISPLAY_WIDTH - 1){return;}
    if (x + width > DISPLAY_WIDTH) { // no -1 here, x alone is width 1
        width = DISPLAY_WIDTH - x;
    }
    oled_goto_xpix_y(x,line);
    oled_data(&displayBuffer[line][x], width);
}
oled_drawBitmap()
uint8_t oled_drawBitmap (uint8_t x, uint8_t y, const uint8_t picture[], uint8_t width, uint8_t height, uint8_t color)
oled_drawCircle()
uint8_t oled_drawCircle (uint8_t center_x, uint8_t center_y, uint8_t radius, uint8_t color)
{
    uint8_t result;
    int16_t f = 1 - radius;
    int16_t ddF_x = 1;
    int16_t ddF_y = -2 * radius;
    int16_t x = 0;
    int16_t y = radius;
    result = oled_drawPixel(center_x  , center_y+radius, color);
    result = oled_drawPixel(center_x  , center_y-radius, color);
    result = oled_drawPixel(center_x+radius, center_y  , color);
    result = oled_drawPixel(center_x-radius, center_y  , color);
    while (x<y) {
        if (f >= 0) {
            y--;
            ddF_y += 2;
            f += ddF_y;
        }
        x++;
        ddF_x += 2;
        f += ddF_x;
        result = oled_drawPixel(center_x + x, center_y + y, color);
        result = oled_drawPixel(center_x - x, center_y + y, color);
        result = oled_drawPixel(center_x + x, center_y - y, color);
        result = oled_drawPixel(center_x - x, center_y - y, color);
        result = oled_drawPixel(center_x + y, center_y + x, color);
        result = oled_drawPixel(center_x - y, center_y + x, color);
        result = oled_drawPixel(center_x + y, center_y - x, color);
        result = oled_drawPixel(center_x - y, center_y - x, color);
    }
    return result;
}
Referenced by oled_fillCircle().
oled_drawLine()
uint8_t oled_drawLine (uint8_t x1, uint8_t y1, uint8_t x2, uint8_t y2, uint8_t color)
{
    uint8_t result;
    int dx =  abs(x2-x1), sx = x1<x2 ? 1 : -1;
    int dy = -abs(y2-y1), sy = y1<y2 ? 1 : -1;
    int err = dx+dy, e2; /* error value e_xy */
    while(1){
        result = oled_drawPixel(x1, y1, color);
        if (x1==x2 && y1==y2) break;
        e2 = 2*err;
        if (e2 > dy) { err += dy; x1 += sx; } /* e_xy+e_x > 0 */
        if (e2 < dx) { err += dx; y1 += sy; } /* e_xy+e_y < 0 */
    }
    return result;
}
Referenced by display_init(), oled_drawRect(), and oled_fillRect().
oled_drawPixel()
uint8_t oled_drawPixel (uint8_t x, uint8_t y, uint8_t color)
{
    if( x > DISPLAY_WIDTH-1 || y > (DISPLAY_HEIGHT-1)) return 1; // out of Display
    if( color == WHITE){
        displayBuffer[(y / 8)][x] |= (1 << (y % 8));
    } else {
        displayBuffer[(y / 8)][x] &= ~(1 << (y % 8));
    }
    return 0;
}
Referenced by oled_drawBitmap(), oled_drawCircle(), and oled_drawLine().
oled_drawRect()
uint8_t oled_drawRect (uint8_t px1, uint8_t py1, uint8_t px2, uint8_t py2, uint8_t color)
{
    uint8_t result;
    result = oled_drawLine(px1, py1, px2, py1, color);
    result = oled_drawLine(px2, py1, px2, py2, color);
    result = oled_drawLine(px2, py2, px1, py2, color);
    result = oled_drawLine(px1, py2, px1, py1, color);
    return result;
}
oled_fillCircle()
uint8_t oled_fillCircle (uint8_t center_x, uint8_t center_y, uint8_t radius, uint8_t color)
{
    uint8_t result;
    for(uint8_t i=0; i<= radius;i++){
        result = oled_drawCircle(center_x, center_y, i, color);
    }
    return result;
}
oled_fillRect()
uint8_t oled_fillRect (uint8_t px1, uint8_t py1, uint8_t px2, uint8_t py2, uint8_t color)
{
    uint8_t result;
    if( px1 > px2){
        uint8_t temp = px1;
        px1 = px2;
        px2 = temp;
        temp = py1;
        py1 = py2;
        py2 = temp;
    }
    for (uint8_t i=0; i<=(py2-py1); i++){
        result = oled_drawLine(px1, py1+i, px2, py1+i, color);
    }
    return result;
}
oled_flip()
void oled_flip (uint8_t flipping)
{
    uint8_t command[2] = {0xC8, 0xA1};
    switch(flipping){
        case 0:
            // normal mode default at init (needs to be reload data to display)
            command[0] = 0xC8;
            command[1] = 0xA1;
            oled_command(command, sizeof(command));
            break;
        case 1:
            // flip horizontal && vertical (needs to be reload data to display)
            command[0] = 0xC0;
            command[1] = 0xA0;
            oled_command(command, sizeof(command));
            break;
        case 2:
            // flip vertical (immediate without reload data to display)
            command[0] = 0xC0;
            oled_command(command, sizeof(command));
            break;
        case 3:
            // flip horizontal (needs to be reload data to display)
            command[1] = 0xA0;
            oled_command(command, sizeof(command));
        default:
            // do nothing
            break;
    }
}
oled_goto_xpix_y()
void oled_goto_xpix_y (uint8_t x, uint8_t y)
{
    if( x > (DISPLAY_WIDTH) || y > (DISPLAY_HEIGHT/8-1)) return;// out of display
    cursorPosition.x=x;
    cursorPosition.y=y;
#if defined (SSD1306) || defined (SSD1309)
    uint8_t commandSequence[] = {0xb0+y, 0x21, x, 0x7f};
#elif defined SH1106
    uint8_t commandSequence[] = {0xb0+y, 0x21, 0x00+((2+x) & (0x0f)), 0x10+( ((2+x) & (0xf0)) >> 4 ), 0x7f};
#endif
    oled_command(commandSequence, sizeof(commandSequence));
}
Referenced by oled_display_block(), and oled_gotoxy().
oled_gotoxy()
void oled_gotoxy (uint8_t x, uint8_t y)
{
    x = x * sizeof(FONT[0]);
    oled_goto_xpix_y(x,y);
}
Referenced by display_init(), display_show_data(), oled_clrscr(), oled_display(), oled_home(), and oled_putc().
oled_home()
void oled_home (void)
                    {
    oled_gotoxy(0, 0);
}
Referenced by oled_clrscr().
oled_init()
void oled_init (uint8_t dispAttr)
{
#if defined I2C
    // i2c_init();
    twi_init();
#elif defined SPI
    DDRB |= (1 << PB2)|(1 << PB3)|(1 << PB5);
    SPCR = (1 << SPE)|(1<<MSTR)|(1<<SPR0);
    OLED_DDR |= (1 << CS_PIN)|(1 << DC_PIN)|(1 << RES_PIN);
    OLED_PORT |= (1 << CS_PIN)|(1 << DC_PIN)|(1 << RES_PIN);
    OLED_PORT &= ~(1 << RES_PIN);
    _delay_ms(10);
    OLED_PORT |= (1 << RES_PIN);
#endif
    uint8_t commandSequence[sizeof(init_sequence)+1];
    for (uint8_t i = 0; i < sizeof (init_sequence); i++) {
        commandSequence[i] = (pgm_read_byte(&init_sequence[i]));
    }
    commandSequence[sizeof(init_sequence)]=(dispAttr);
    oled_command(commandSequence, sizeof(commandSequence));
    oled_clrscr();
}
Referenced by display_init().
oled_invert()
void oled_invert (uint8_t invert)
{
    uint8_t commandSequence[1];
    if (invert != YES) {
        commandSequence[0] = 0xA6;
    } else {
        commandSequence[0] = 0xA7;
    }
    oled_command(commandSequence, 1);
}
oled_putc()
void oled_putc (char c)
                      {
    switch (c) {
        case '\b':
            // backspace
            oled_gotoxy(cursorPosition.x-charMode, cursorPosition.y);
            oled_putc(' ');
            oled_gotoxy(cursorPosition.x-charMode, cursorPosition.y);
            break;
        case '\t':
            // tab
            if( (cursorPosition.x+charMode*4) < (DISPLAY_WIDTH/ sizeof(FONT[0])-charMode*4) ){
                oled_gotoxy(cursorPosition.x+charMode*4, cursorPosition.y);
            }else{
                oled_gotoxy(DISPLAY_WIDTH/ sizeof(FONT[0]), cursorPosition.y);
            }
            break;
        case '\n':
            // linefeed
            if(cursorPosition.y < (DISPLAY_HEIGHT/8-1)){
                oled_gotoxy(cursorPosition.x, cursorPosition.y+charMode);
            }
            break;
        case '\r':
            // carrige return
            oled_gotoxy(0, cursorPosition.y);
            break;
        default:
            // char doesn't fit in line
            if( (cursorPosition.x >= DISPLAY_WIDTH-sizeof(FONT[0])) || (c < ' ') ) break;
            // mapping char
            c -= ' ';
            if (c >= pgm_read_byte(&special_char[0][1]) ) {
                char temp = c;
                c = 0xff;
                for (uint8_t i=0; pgm_read_byte(&special_char[i][1]) != 0xff; i++) {
                    if ( pgm_read_byte(&special_char[i][0])-' ' == temp ) {
                        c = pgm_read_byte(&special_char[i][1]);
                        break;
                    }
                }
                if ( c == 0xff ) break;
            }
            // print char at display
#ifdef GRAPHICMODE
            if (charMode == DOUBLESIZE) {
                uint16_t doubleChar[sizeof(FONT[0])];
                uint8_t dChar;
                if ((cursorPosition.x+2*sizeof(FONT[0]))>DISPLAY_WIDTH) break;
                for (uint8_t i=0; i < sizeof(FONT[0]); i++) {
                    doubleChar[i] = 0;
                    dChar = pgm_read_byte(&(FONT[(uint8_t)c][i]));
                    for (uint8_t j=0; j<8; j++) {
                        if ((dChar & (1 << j))) {
                            doubleChar[i] |= (1 << (j*2));
                            doubleChar[i] |= (1 << ((j*2)+1));
                        }
                    }
                }
                for (uint8_t i = 0; i < sizeof(FONT[0]); i++)
                {
                    // load bit-pattern from flash
                    displayBuffer[cursorPosition.y+1][cursorPosition.x+(2*i)] = doubleChar[i] >> 8;
                    displayBuffer[cursorPosition.y+1][cursorPosition.x+(2*i)+1] = doubleChar[i] >> 8;
                    displayBuffer[cursorPosition.y][cursorPosition.x+(2*i)] = doubleChar[i] & 0xff;
                    displayBuffer[cursorPosition.y][cursorPosition.x+(2*i)+1] = doubleChar[i] & 0xff;
                }
                cursorPosition.x += sizeof(FONT[0])*2;
            } else {
                if ((cursorPosition.x+sizeof(FONT[0]))>DISPLAY_WIDTH) break;
                for (uint8_t i = 0; i < sizeof(FONT[0]); i++)
                {
                    // load bit-pattern from flash
                    displayBuffer[cursorPosition.y][cursorPosition.x+i] =pgm_read_byte(&(FONT[(uint8_t)c][i]));
                }
                cursorPosition.x += sizeof(FONT[0]);
            }
#elif defined TEXTMODE
            if (charMode == DOUBLESIZE) {
                uint16_t doubleChar[sizeof(FONT[0])];
                uint8_t dChar;
                if ((cursorPosition.x+2*sizeof(FONT[0]))>DISPLAY_WIDTH) break;
                for (uint8_t i=0; i < sizeof(FONT[0]); i++) {
                    doubleChar[i] = 0;
                    dChar = pgm_read_byte(&(FONT[(uint8_t)c][i]));
                    for (uint8_t j=0; j<8; j++) {
                        if ((dChar & (1 << j))) {
                            doubleChar[i] |= (1 << (j*2));
                            doubleChar[i] |= (1 << ((j*2)+1));
                        }
                    }
                }
                uint8_t data[sizeof(FONT[0])*2];
                for (uint8_t i = 0; i < sizeof(FONT[0]); i++)
                {
                    // print font to ram, print 6 columns
                    data[i<<1]=(doubleChar[i] & 0xff);
                    data[(i<<1)+1]=(doubleChar[i] & 0xff);
                }
                oled_data(data, sizeof(FONT[0])*2);
#if defined (SSD1306) || defined (SSD1309)
                uint8_t commandSequence[] = {0xb0+cursorPosition.y+1,
                    0x21,
                    cursorPosition.x,
                    0x7f};
#elif defined SH1106
                uint8_t commandSequence[] = {0xb0+cursorPosition.y+1,
                    0x21,
                    0x00+((2+cursorPosition.x) & (0x0f)),
                    0x10+( ((2+cursorPosition.x) & (0xf0)) >> 4 ),
                    0x7f};
#endif
                oled_command(commandSequence, sizeof(commandSequence));
                for (uint8_t i = 0; i < sizeof(FONT[0]); i++)
                {
                    // print font to ram, print 6 columns
                    data[i<<1]=(doubleChar[i] >> 8);
                    data[(i<<1)+1]=(doubleChar[i] >> 8);
                }
                oled_data(data, sizeof(FONT[0])*2);
                commandSequence[0] = 0xb0+cursorPosition.y;
#if defined (SSD1306) || defined (SSD1309)
                commandSequence[2] = cursorPosition.x+(2*sizeof(FONT[0]));
#elif defined SH1106
                commandSequence[2] = 0x00+((2+cursorPosition.x+(2*sizeof(FONT[0]))) & (0x0f));
                commandSequence[3] = 0x10+( ((2+cursorPosition.x+(2*sizeof(FONT[0]))) & (0xf0)) >> 4 );
#endif
                oled_command(commandSequence, sizeof(commandSequence));
                cursorPosition.x += sizeof(FONT[0])*2;
            } else {
                uint8_t data[sizeof(FONT[0])];
                if ((cursorPosition.x+sizeof(FONT[0]))>DISPLAY_WIDTH) break;
                for (uint8_t i = 0; i < sizeof(FONT[0]); i++)
                {
                    // print font to ram, print 6 columns
                    data[i]=(pgm_read_byte(&(FONT[(uint8_t)c][i])));
                }
                oled_data(data, sizeof(FONT[0]));
                cursorPosition.x += sizeof(FONT[0]);
            }
#endif
            break;
    }
}
Referenced by oled_putc(), oled_puts(), and oled_puts_p().
oled_puts()
void oled_puts (const char * s)
{
    while (*s) {
        oled_putc(*s++);
    }
}
Referenced by display_init(), and display_show_data().
oled_puts_p()
void oled_puts_p (const char * progmem_s)
{
    register uint8_t c;
    while ((c = pgm_read_byte(progmem_s++))) {
        oled_putc(c);
    }
}
oled_set_contrast()
void oled_set_contrast (uint8_t contrast)
{
    uint8_t commandSequence[2] = {0x81, contrast};
    oled_command(commandSequence, sizeof(commandSequence));
}
oled_sleep()
void oled_sleep (uint8_t sleep)
{
    uint8_t commandSequence[1];
    if (sleep != YES) {
        commandSequence[0] = 0xAF;
    } else {
        commandSequence[0] = 0xAE;
    }
    oled_command(commandSequence, 1);
}