Watering system with Arudino UNO without Arduino libraries: lib/storage/storage.h File Reference
storage.h File Reference
#include <dataset.h>
#include <avr/io.h>
#include <time.h>
Classes
struct storage_t
Functions
void storage_init (storage_t *storage)
void EEPROM_write (uint16_t addr, uint8_t val)
uint8_t EEPROM_read (uint16_t addr)
void storage_write (storage_t *storage, dataset_t *data)
void storage_read (storage_t *storage, dataset_t *data, uint8_t pos)
Function Documentation
EEPROM_read()
uint8_t EEPROM_read (uint16_t addr)
{
    /* Wait for completion of previous write */
    while(EECR & (1<<EEPE));
    /* Set up address register */
    EEAR = addr;
    /* Start eeprom read by writing EERE */
    EECR |= (1<<EERE);
    /* Return data from Data Register */
    return EEDR;
}
Referenced by storage_read().
EEPROM_write()
void EEPROM_write (uint16_t addr, uint8_t val)
{
    /* Wait for completion of previous write */
    while(EECR & (1<<EEPE)) ;
    /* Set up address and Data Registers */
    EEAR = addr;
    EEDR = val;
    /* Write logical one to EEMPE */
    EECR |= (1<<EEMPE);
    /* Start eeprom write by setting EEPE */
    EECR |= (1<<EEPE);
}
Referenced by storage_write().
storage_init()
void storage_init (storage_t * storage)
{
    storage->buffer_start = 0;
}
Referenced by main().
storage_read()
void storage_read (storage_t * storage, dataset_t * data, uint8_t pos)
{
    uint8_t *iter = ((uint8_t *)data);
    while(pos > storage->buffer_start)
        pos -= 1000 / sizeof(dataset_t);
    for(uint8_t i = 0; i < sizeof(dataset_t); i++)
    {
        iter[i] = EEPROM_read(i + storage->buffer_start - pos*sizeof(dataset_t));
    }
}
Referenced by cmd_handler().
storage_write()
void storage_write (storage_t * storage, dataset_t * data)
{
    uint8_t *iter = ((uint8_t *)data);
    for(uint8_t i = 0; i < sizeof(dataset_t); i++)
    {
        EEPROM_write(i + storage->buffer_start, iter[i]);
    }
    storage->buffer_start += sizeof(dataset_t);
    if(storage->buffer_start + sizeof(dataset_t) > 1000)
    {
        storage->buffer_start = 0;
    }
}
Referenced by main().