Watering system with Arudino UNO without Arduino libraries: lib/watering/watering.c File Reference
watering.c File Reference
#include "watering.h"
Functions
void watering_init (watering_t *watering, servo_t *servo)
void watering_set_limit (watering_t *watering, uint16_t min, uint16_t max)
void watering_handler (watering_t *watering, dataset_t *data)
Function Documentation
watering_handler()
void watering_handler (watering_t * watering, dataset_t * data)
{
    if(watering->servo->value != 160 && watering->servo->value != 20)
        servo_set_value(watering->servo, 20);
    if(watering->servo->value == 20 && data->moist < watering->min)
        servo_set_value(watering->servo, 160);
    if(watering->servo->value != 20 && data->moist > watering->max)
        servo_set_value(watering->servo, 20);
}
Referenced by main().
watering_init()
void watering_init (watering_t * watering, servo_t * servo)
{
    watering->servo = servo;
    servo_set_value(watering->servo, 0);
}
Referenced by main().
watering_set_limit()
void watering_set_limit (watering_t * watering, uint16_t min, uint16_t max)
{
    watering->min = min;
    watering->max = max;
}
Referenced by main().